all:
	$(MAKE) -C CJson all
#	$(MAKE) -C Ntp all
#	$(MAKE) -C FFT all
	$(MAKE) -C TSocket all
	$(MAKE) -C List all
	$(MAKE) -C Base64 all	
#	$(MAKE) -C wipn all
	$(MAKE) -C UsrMem all
	$(MAKE) -C UsrString all
#	$(MAKE) -C opencv2_4_9 all
#	$(MAKE) -C libsmtp all
	$(MAKE) -C polarssl-1.0.0 all
#	$(MAKE) -C libavi all
#	$(MAKE) -C libiniparser all
#	$(MAKE) -C libmp4 all
#	$(MAKE) -C libp2p all	
#	$(MAKE) -C p2psocket all
	$(MAKE) -C MyAuthor 
	$(MAKE) -C log all
	$(MAKE) -C mosquitto-1.4.4 all	
	$(MAKE) -C Bin2Hex all
	$(MAKE) -C libeventtask all
	$(MAKE) -C libjpeg all
	$(MAKE) -C Config all
#	$(MAKE) -C mxml-3.2 all
	$(MAKE) -C librtmp all
#	$(MAKE) -C curl-7.77.0 all
		
clean:
	$(MAKE) -C CJson clean
#	$(MAKE) -C Ntp clean
#	$(MAKE) -C FFT clean
	$(MAKE) -C TSocket clean
	$(MAKE) -C List clean
	$(MAKE) -C Base64 clean
#	$(MAKE) -C wipn clean
	$(MAKE) -C UsrMem clean
	$(MAKE) -C UsrString clean
#	$(MAKE) -C opencv2_4_9 clean
#	$(MAKE) -C libsmtp clean
	$(MAKE) -C polarssl-1.0.0 clean
#	$(MAKE) -C libavi clean
#	$(MAKE) -C libiniparser clean
#	$(MAKE) -C libmp4 clean
#	$(MAKE) -C libp2p clean	
#	$(MAKE) -C p2psocket clean
	$(MAKE) -C MyAuthor clean
	$(MAKE) -C log clean
	$(MAKE) -C mosquitto-1.4.4 clean
	$(MAKE) -C Bin2Hex clean
	$(MAKE) -C libeventtask clean
	$(MAKE) -C libjpeg clean
	$(MAKE) -C Config clean
#	$(MAKE) -C mxml-3.2 clean
	$(MAKE) -C librtmp clean
#	$(MAKE) -C curl-7.77.0 clean
