all:
	$(MAKE) -C HttpAPI all
	$(MAKE) -C JsonAPI all
	$(MAKE) -C MqttAPI all
	$(MAKE) -C CICTAPI all
	$(MAKE) -C HJ212API all
	$(MAKE) -C WebServer all
	$(MAKE) -C Rtmp all
clean:
	$(MAKE) -C HttpAPI clean
	$(MAKE) -C HttpAPI clean
	$(MAKE) -C JsonAPI clean
	$(MAKE) -C MqttAPI clean	
	$(MAKE) -C CICTAPI clean
	$(MAKE) -C HJ212API clean
	$(MAKE) -C WebServer clean
	$(MAKE) -C Rtmp clean

